const NOTES = [
  {id:'Fs3',disp:'F♯',name:'Fs',oct:3,pos:-6,acc:true, fingerings:[{v:[1,2,3],desc:'standard'}]},
  {id:'G3', disp:'G', name:'G', oct:3,pos:-5,acc:false,fingerings:[{v:[1,3],desc:'standard'}]},
  {id:'Gs3',disp:'G♯',name:'Gs',oct:3,pos:-5,acc:true, fingerings:[{v:[2,3],desc:'standard'}]},
  {id:'A3', disp:'A', name:'A', oct:3,pos:-4,acc:false,fingerings:[{v:[1,2],desc:'standard'},{v:[3],desc:'alternate'}]},
  {id:'As3',disp:'A♯',name:'As',oct:3,pos:-4,acc:true, fingerings:[{v:[1],desc:'standard'}]},
  {id:'B3', disp:'B', name:'B', oct:3,pos:-3,acc:false,fingerings:[{v:[2],desc:'standard'}]},
  {id:'C4', disp:'C', name:'C', oct:4,pos:-2,acc:false,fingerings:[{v:[],desc:'open'}]},
  {id:'Cs4',disp:'C♯',name:'Cs',oct:4,pos:-2,acc:true, fingerings:[{v:[1,2,3],desc:'standard'}]},
  {id:'D4', disp:'D', name:'D', oct:4,pos:-1,acc:false,fingerings:[{v:[1,3],desc:'standard'}]},
  {id:'Ds4',disp:'D♯',name:'Ds',oct:4,pos:-1,acc:true, fingerings:[{v:[2,3],desc:'standard'}]},
  {id:'E4', disp:'E', name:'E', oct:4,pos:0, acc:false,fingerings:[{v:[1,2],desc:'standard'},{v:[3],desc:'alternate'}]},
  {id:'F4', disp:'F', name:'F', oct:4,pos:1, acc:false,fingerings:[{v:[1],desc:'standard'}]},
  {id:'Fs4',disp:'F♯',name:'Fs',oct:4,pos:1, acc:true, fingerings:[{v:[2],desc:'standard'}]},
  {id:'G4', disp:'G', name:'G', oct:4,pos:2, acc:false,fingerings:[{v:[],desc:'open'},{v:[1,3],desc:'alternate'}]},
  {id:'Gs4',disp:'G♯',name:'Gs',oct:4,pos:2, acc:true, fingerings:[{v:[2,3],desc:'standard'}]},
  {id:'A4', disp:'A', name:'A', oct:4,pos:3, acc:false,fingerings:[{v:[1,2],desc:'standard'},{v:[3],desc:'alternate'}]},
  {id:'As4',disp:'A♯',name:'As',oct:4,pos:3, acc:true, fingerings:[{v:[1],desc:'standard'}]},
  {id:'B4', disp:'B', name:'B', oct:4,pos:4, acc:false,fingerings:[{v:[2],desc:'standard'}]},
  {id:'C5', disp:'C', name:'C', oct:5,pos:5, acc:false,fingerings:[{v:[],desc:'open'},{v:[2,3],desc:'alternate'}]},
  {id:'Cs5',disp:'C♯',name:'Cs',oct:5,pos:5, acc:true, fingerings:[{v:[1,2],desc:'standard'}]},
  {id:'D5', disp:'D', name:'D', oct:5,pos:6, acc:false,fingerings:[{v:[1],desc:'standard'},{v:[1,3],desc:'alternate'}]},
  {id:'Ds5',disp:'D♯',name:'Ds',oct:5,pos:6, acc:true, fingerings:[{v:[2],desc:'standard'},{v:[2,3],desc:'alternate'}]},
  {id:'E5', disp:'E', name:'E', oct:5,pos:7, acc:false,fingerings:[{v:[],desc:'open'},{v:[1,2],desc:'alternate'},{v:[3],desc:'alternate'}]},
  {id:'F5', disp:'F', name:'F', oct:5,pos:8, acc:false,fingerings:[{v:[1],desc:'standard'}]},
  {id:'Fs5',disp:'F♯',name:'Fs',oct:5,pos:8, acc:true, fingerings:[{v:[2],desc:'standard'}]},
  {id:'G5', disp:'G', name:'G', oct:5,pos:9, acc:false,fingerings:[{v:[],desc:'open'},{v:[1,3],desc:'alternate'}]},
  {id:'Gs5',disp:'G♯',name:'Gs',oct:5,pos:9, acc:true, fingerings:[{v:[2,3],desc:'standard'}]},
  {id:'A5', disp:'A', name:'A', oct:5,pos:10,acc:false,fingerings:[{v:[1,2],desc:'standard'},{v:[3],desc:'alternate'}]},
  {id:'As5',disp:'A♯',name:'As',oct:5,pos:10,acc:true, fingerings:[{v:[1],desc:'standard'}]},
  {id:'B5', disp:'B', name:'B', oct:5,pos:11,acc:false,fingerings:[{v:[2],desc:'standard'}]},
  {id:'C6', disp:'C', name:'C', oct:6,pos:12,acc:false,fingerings:[{v:[],desc:'open'}]},
];

const ID_SEMI = {
  'Fs3':6,'G3':7,'Gs3':8,'A3':9,'As3':10,'B3':11,
  'C4':12,'Cs4':13,'D4':14,'Ds4':15,'E4':16,
  'F4':17,'Fs4':18,'G4':19,'Gs4':20,'A4':21,'As4':22,'B4':23,
  'C5':24,'Cs5':25,'D5':26,'Ds5':27,'E5':28,'F5':29,
  'Fs5':30,'G5':31,'Gs5':32,'A5':33,'As5':34,'B5':35,'C6':36
};
